# NumPy

NumPy is a Python package that allows the efficient handling on and operation on large arrays of numerical data. It's one of the most fundamental libraies for quantitative analysis.

In [3]:
import numpy as np

- NumPy Arrays  
- NumPy Indexing and Selection  
- NumPy Operations  
- NumPy Exercise (and Solution)

## Regular ndarray Object

In [4]:
# creating numpy array by casting a list
my_list = [1, 2, 3]
np.array(my_list)

array([1, 2, 3])

In [5]:
type(np.array(my_list))

numpy.ndarray

In [6]:
# creating a numpy array with the build in range function of python
a = np.array(range(24))

In [7]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [8]:
# creating a numpy array with the arange function of numpy
a1 = np.arange(0,5)
a1

array([0, 1, 2, 3, 4])

In [9]:
a2 = np.arange(1,11,2)
a2

array([1, 3, 5, 7, 9])

In [10]:
# creating arrays of zeros
np.zeros(3)

array([0., 0., 0.])

In [11]:
# same for two-dimensional arrays
# passing tuple to array function (index 1 rows, index two columns)
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
# creating arrays of ones
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
# returning evenly spaced numbers over a specified interval
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [14]:
# creating a matrix from a nested list
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np_matrix = np.array(my_matrix)

In [15]:
np_matrix # two dimensional matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
type(np_matrix)

numpy.ndarray

In [17]:
# numpy array as matrix
b = a.reshape((4, 6))

In [18]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [19]:
# creating an identiy matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
# numpy's random library
# used to model something like monte carlo simulation
np.random.rand(1) # retunrs random float between zero and one

array([0.71013747])

In [21]:
np.random.rand(5,4) # returns 5 x 4 matrix with random numbers berween zero and one
# uniform distribution, every number has the same odds of being picked

array([[0.74863352, 0.45561455, 0.89107272, 0.39950339],
       [0.80285729, 0.02825484, 0.91752523, 0.57986701],
       [0.25002283, 0.40176826, 0.18699582, 0.29964619],
       [0.41968148, 0.20244305, 0.82502061, 0.07928202],
       [0.2120802 , 0.6738445 , 0.96050065, 0.30683134]])

In [22]:
np.random.randn(5) # returns sample from the standard_normal distribution

array([-1.87972189, -1.74127853, -0.3683802 , -0.29298564,  0.54312332])

In [23]:
np.random.randn(5,5)

array([[ 0.24570172, -0.73558165, -0.11132909,  0.62292776,  1.93983935],
       [ 0.75812708,  1.34518995,  0.55065869, -0.5677883 , -1.21222852],
       [ 0.38025219,  0.27777649,  0.44784683, -0.61645469, -0.21037203],
       [ 0.6876594 , -0.09646513, -0.42571356,  0.74218947,  0.10373384],
       [ 2.11966841,  0.23571521,  0.03252126,  0.59705661, -0.36515957]])

In [24]:
np.random.randint(1,100) # returns random integer from the "discrete uniform" distribution 

29

In [25]:
np.random.randint(1,100,10)

array([99, 11,  3, 72, 90,  7, 67, 40,  4, 60])

In [26]:
# array attributes and methods that are useful
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0,50,10)
ranarr

array([11,  3, 10, 49, 31, 41, 22, 44,  3,  5])

In [28]:
# return an array with the same data but a different shape
arr.reshape(5,5) # reshape array to 5 by 5 matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
arr.shape # returns shape of one dimensional array

(25,)

In [30]:
arr.reshape(5,5).shape # shape of 5 by 5 matrix

(5, 5)

In [31]:
arr.dtype # data type of the array

dtype('int64')

In [32]:
ranarr.max() # max number in an array

np.int64(49)

In [33]:
ranarr.argmax() # index location of max number in an array

np.int64(3)

In [34]:
ranarr.min() # min number in an array

np.int64(3)

In [35]:
ranarr.argmin() # index location of min number in an array

np.int64(1)

## NumPy Operations

In [36]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
# array addition on element by element basis
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
# array multiplication on element by element basis
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [39]:
# substraction
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
# division
arr / arr # returns warning if 0 is in array
# 0/0 gets replaced with nan

/var/folders/7c/6tn50bjd30l3zb0p8_7mr94m0000gn/T/ipykernel_10441/897384303.py:2: RuntimeWarning: invalid value encountered in divide
  arr / arr # returns warning if 0 is in array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [41]:
1/arr # 1/0 gets replaced by infinity

/var/folders/7c/6tn50bjd30l3zb0p8_7mr94m0000gn/T/ipykernel_10441/659140530.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr # 1/0 gets replaced by infinity


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [42]:
# exponentials
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [43]:
# numpy comes along with array functions
np.sqrt(arr) # square root of every element

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [44]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [45]:
# what's the maximum value in an array
np.max(arr)

np.int64(9)

In [46]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [47]:
np.log(arr)

/var/folders/7c/6tn50bjd30l3zb0p8_7mr94m0000gn/T/ipykernel_10441/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## NumPy for Indexing and Selection

In [48]:
arr = np.arange(0,11)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
# bracket indexing and selection
# element at index 8
arr[8]

np.int64(8)

In [51]:
# slice notation
arr[1:5]

array([1, 2, 3, 4])

In [52]:
# everything up to a certain position but not including it
arr[:5]

array([0, 1, 2, 3, 4])

In [53]:
# everything from a certain position up to the end
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
# broadcasting a reasignment
# grab a slice and set it equal to a certain value
arr[0:5] = 100

In [55]:
arr # five elements now have the number 100, this is known as broadcasting

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [56]:
# resetting the array
arr = np.arange(0,11)

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
# example: slice of array is a pointer to the original array
# changing the slice changes the original array as well
# the data is not actually copied (avoids memory problems)
slice_of_arr = arr[0:6]

In [59]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [60]:
slice_of_arr[:] = 99

In [61]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [62]:
arr # notice that slice was just a pointer

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [63]:
# if you want to have a copy you've to explicitly say so
arr_copy = arr.copy()

In [64]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [65]:
arr_copy[:] = 200

In [66]:
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [67]:
arr # change doesn't affect original array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [68]:
# indexing twodimensional array (matrix)
# matr[row, col]
# or matr[row][col]
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [69]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [70]:
# indexing entire row
mat[0] # returns first row

array([ 5, 10, 15])

In [71]:
# grab individual element
# matr[row, col]
mat[1,1] # second row, second element

np.int64(25)

In [72]:
# or matr[row][col]
mat[2][2] # third row, third element

np.int64(45)

In [73]:
# slicing a matrix
mat[:2,] # grabbing row two and three

array([[ 5, 10, 15],
       [20, 25, 30]])

In [74]:
mat[:2,1:] # grabbing row two and three, column two and three

array([[10, 15],
       [25, 30]])

In [75]:
mat[1:3,0:2] # grabbing another square

array([[20, 25],
       [35, 40]])

In [76]:
# or
mat[1:,:2] # grabbing another square

array([[20, 25],
       [35, 40]])

In [77]:
# conditional selection
arr = np.arange(1,11)

In [78]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
# grabbing elements with some sort of comparison operator
arr > 4 # returns an array of boolean values

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [80]:
bool_arr = arr > 4

In [81]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [82]:
# passing filtered array to original array
arr[bool_arr] # returns only the values where the boolean values happen to be true

array([ 5,  6,  7,  8,  9, 10])

In [83]:
# shortcut
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [84]:
# can be done for any sort of comparison operator
arr[arr <= 9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])