## Vectorized Backtesting: Vectorization with NumPy and pandas

*[Coding along with Python for Algorithmic Trading, Yves Hilpisch, O'Reilly, 1st edition November 2020, ISBN-13: 978-1492053354]*

Testing ideas and hypothesis for an algorithmic trading program is the highly technical part of developing a trading strategy. 

> *Vectorized backtesting is a method of testing trading strategies where all trades are calculated simultaneously using arrays/matrices of historical market data, rather than processing trades one by one in a loop. This approach is typically much faster than event-driven backtesting since it leverages efficient array operations, though it may not capture some real-world trading complexities as accurately (claude.ai).*

### Vectorization with NumPy

The NumPy package for numerical computing brings vectorization into the Python ecosystem. According to its [website](https://numpy.org/), *"the NumPy vectorization, indexing, and broadcasting concepts are the de-facto standards of array computing today."* NumPy allows for vectorization techniques based on the regular array class `ndarray`.

In [16]:
import numpy as np

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


In [17]:
v = [1, 2, 3, 4, 5] # python list object

In [18]:
a = np.array(v) # instantiating and ndarray object based on a list array
a

array([1, 2, 3, 4, 5])

In [19]:
type(a) # checking the type ot the object

numpy.ndarray

In [20]:
# scalar multiplication in vectorized fashion
2 * a

array([ 2,  4,  6,  8, 10])

In [21]:
0.5 * a + 2 # linear transformation in vectorized fashion

array([2.5, 3. , 3.5, 4. , 4.5])

__Transition from a one-dimensional array (a vector) to a higher-dimensional structure (a matrix)__

In [22]:
# arange() creates one-dimensional ndarray object
# reshape() reshapes it to 2-dimensions
a = np.arange(12).reshape([3,4])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
# scalar multiplication in vectorized fashion
2 * a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [24]:
# calculating the square on vectorized fashion
a ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

__Methods that allow vectorized operations (the "universal functions" of NumPy)__

In [25]:
a.mean() # the mean of all elements by method call

np.float64(5.5)

In [26]:
np.mean(a) # the mean of all elements by universal function

np.float64(5.5)

In [27]:
a.mean(axis=0) # the mean along the first axis by method call

array([4., 5., 6., 7.])

In [28]:
np.mean(a, axis=1) # the mean along the second axis by universal function

array([1.5, 5.5, 9.5])