### Matrix Multiplication

*Studying and coding along with Udemy online course [__„Dive into Deep Learning“__](https://www.udemy.com/course/deeplearning_x/?couponCode=KEEPLEARNING) by Mike X Cohen. The accompanying GitHub repository can be found at [mikexcohen /
DeepUnderstandingOfDeepLearning](https://github.com/mikexcohen/DeepUnderstandingOfDeepLearning/tree/main/math).*

*COURSE: A deep understanding of deep learning<br />
SECTION: Math prerequisites<br />
LECTURE: Matrix multiplication<br />
TEACHER: Mike X Cohen, sincxpress.com*

How to implement matrix multiplication in numpy and pytorch:

### Matrix Multiplication in numpy

In [1]:
# import libraries
import numpy as np
import torch

In [2]:
# first lets create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)
A, B, C

(array([[ 2.1161009 , -0.00257861, -0.89835204, -0.79713724],
        [ 0.66491414,  0.82711215,  0.9283827 , -0.37627094],
        [ 0.10242182,  1.92725344, -0.3368504 ,  0.75624744]]),
 array([[ 0.44535337, -1.2074994 , -0.74590644, -0.44164272, -1.11906585],
        [ 1.98845494,  1.23202102,  0.38000119, -2.02490068, -1.5186329 ],
        [ 1.07284486, -0.3167103 ,  0.26610711, -2.0827152 ,  0.21965946],
        [ 0.2320853 ,  0.02546347,  1.30201765, -1.81547065,  0.06598719]]),
 array([[-0.2535735 ,  1.85924717, -0.54101944,  1.2461293 ,  0.72075959,
          0.68476798,  0.49866076],
        [-0.77161158, -0.44134888,  1.4025791 ,  1.14624606,  0.50651947,
         -1.43377723,  0.51979379],
        [ 1.06665985,  2.60211001, -0.08017182, -1.38487589,  0.13228827,
         -1.78270039, -0.49825896]]))

In [11]:
# multiplications with the @ operator 
# these two work:
print(np.round( A@B   ,2)), print(' ')
print(np.round( C.T@A ,2)) # 
print(np.round( C.T@A ,2)) # C.T -> transposing C
# we're using np.round because it's nicer to read with two decimals

[[-0.21 -2.29 -2.86  2.39 -2.61]
 [ 2.85 -0.09 -0.42 -3.22 -1.82]
 [ 3.69  2.38  1.55 -4.62 -3.07]]
 
[[-0.94  1.42 -0.85  1.3 ]
 [ 3.91  4.65 -2.96  0.65]
 [-0.22  1.01  1.82 -0.16]
 [ 3.26 -1.72  0.41 -2.47]
 [ 1.88  0.67 -0.22 -0.67]
 [ 0.31 -4.62 -1.35 -1.35]
 [ 1.35 -0.53  0.2  -0.97]]
[[-0.94  1.42 -0.85  1.3 ]
 [ 3.91  4.65 -2.96  0.65]
 [-0.22  1.01  1.82 -0.16]
 [ 3.26 -1.72  0.41 -2.47]
 [ 1.88  0.67 -0.22 -0.67]
 [ 0.31 -4.62 -1.35 -1.35]
 [ 1.35 -0.53  0.2  -0.97]]


The following python code creates errors:

`print(np.round( A@C   ,2)), print(' ')`

__ValueError:__ matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

`print(np.round( B@C   ,2)), print(' ')`

__ValueError:__ matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 5)

### Matrix Multiplication in pytorch

In [22]:
# let's create some random matrices with torch
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7) # matrix created with numpy - will this work?
C2 = torch.tensor( C1,dtype=torch.float ) # converting numpy matrix into pytorch data type
A, B, C1, C2, C2.shape

(tensor([[ 0.7876,  0.0736, -0.1742,  1.1398],
         [ 1.9220,  1.3624, -0.8146,  0.2728],
         [-0.4113, -0.8474, -0.7157, -0.3993]]),
 tensor([[ 1.0236, -0.4221,  0.2097, -0.0076, -0.4185],
         [-0.1357,  0.5459, -0.4162,  0.3887, -0.3752],
         [ 0.1158,  1.3547,  0.5483, -0.8488,  0.5548],
         [-0.1706,  0.0947, -0.8883, -1.3763,  0.0480]]),
 array([[ 0.28816659, -0.97872037, -0.58503657, -0.33708158, -0.59127088,
          0.25321073, -0.32696217],
        [-1.64116339, -1.20846599,  2.20518643, -1.18426061,  0.08093544,
         -0.66744648,  0.43569447],
        [-0.08908391, -0.22881402,  0.64443201,  0.28746817,  1.53292133,
          0.05368647, -1.09472459],
        [-0.9199874 ,  0.74565242, -0.52789964, -0.16097511, -0.86085267,
          0.58748591, -1.57414606]]),
 tensor([[ 0.2882, -0.9787, -0.5850, -0.3371, -0.5913,  0.2532, -0.3270],
         [-1.6412, -1.2085,  2.2052, -1.1843,  0.0809, -0.6674,  0.4357],
         [-0.0891, -0.2288,  0.6444,  0.2

In [23]:
# matrix multiplication
print(np.round( A@C1  ,2)), print(' ') # 3x4 and 4x7; pytorch * numpy works quite well

tensor([[-0.9300,  0.0300, -1.0100, -0.5900, -1.7100,  0.8100, -1.8300],
        [-1.8600, -3.1400,  1.2100, -2.5400, -2.5100, -0.3100,  0.4300],
        [ 1.7000,  1.2900, -1.8800,  1.0000, -0.5800,  0.1900,  1.1800]],
       dtype=torch.float64)
 


(None, None)

In [16]:
print(np.round( A@C2  ,2)) # 3x4 and 4x7 again

tensor([[-0.0100,  0.8100, -1.8200,  0.7400, -3.6800,  0.7400, -1.2500],
        [-2.0900,  0.6100,  2.7800, -1.4800,  3.8100, -4.7500,  0.1400],
        [-0.0700,  0.1900, -0.7500,  1.1400,  0.3300, -1.6600,  0.5100]])


In [18]:
print(np.round( A@B   ,2)) # 3x4 and 4x5

tensor([[ 1.6000, -0.6500, -0.2200,  5.7700, -3.2600],
        [-0.8800, -3.0300,  3.6900, -7.1300, 11.7100],
        [ 0.4000, -2.0200, -0.7700,  1.4500, -0.3100]])


The following python code creates errors:

`print(np.round( A@B   ,2)), print(' ')`

__RuntimeError:__ mat1 and mat2 shapes cannot be multiplied (3x4 and 5x4)