### Matrix Multiplication

*Studying and coding along with Udemy online course [__„Dive into Deep Learning“__](https://www.udemy.com/course/deeplearning_x/?couponCode=KEEPLEARNING) by Mike X Cohen. The accompanying GitHub repository can be found at [mikexcohen /
DeepUnderstandingOfDeepLearning](https://github.com/mikexcohen/DeepUnderstandingOfDeepLearning/tree/main/math).*

*COURSE: A deep understanding of deep learning<br />
SECTION: Math prerequisites<br />
LECTURE: Matrix multiplication<br />
TEACHER: Mike X Cohen, sincxpress.com*

How to implement matrix multiplication in numpy and pytorch:

### Matrix Multiplication in numpy

In [1]:
# import libraries
import numpy as np
import torch

In [2]:
# first lets create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)
A, B, C

(array([[ 2.1161009 , -0.00257861, -0.89835204, -0.79713724],
        [ 0.66491414,  0.82711215,  0.9283827 , -0.37627094],
        [ 0.10242182,  1.92725344, -0.3368504 ,  0.75624744]]),
 array([[ 0.44535337, -1.2074994 , -0.74590644, -0.44164272, -1.11906585],
        [ 1.98845494,  1.23202102,  0.38000119, -2.02490068, -1.5186329 ],
        [ 1.07284486, -0.3167103 ,  0.26610711, -2.0827152 ,  0.21965946],
        [ 0.2320853 ,  0.02546347,  1.30201765, -1.81547065,  0.06598719]]),
 array([[-0.2535735 ,  1.85924717, -0.54101944,  1.2461293 ,  0.72075959,
          0.68476798,  0.49866076],
        [-0.77161158, -0.44134888,  1.4025791 ,  1.14624606,  0.50651947,
         -1.43377723,  0.51979379],
        [ 1.06665985,  2.60211001, -0.08017182, -1.38487589,  0.13228827,
         -1.78270039, -0.49825896]]))

In [11]:
# multiplications with the @ operator 
# these two work:
print(np.round( A@B   ,2)), print(' ')
print(np.round( C.T@A ,2)) # 
print(np.round( C.T@A ,2)) # C.T -> transposing C
# we're using np.round because it's nicer to read with two decimals

[[-0.21 -2.29 -2.86  2.39 -2.61]
 [ 2.85 -0.09 -0.42 -3.22 -1.82]
 [ 3.69  2.38  1.55 -4.62 -3.07]]
 
[[-0.94  1.42 -0.85  1.3 ]
 [ 3.91  4.65 -2.96  0.65]
 [-0.22  1.01  1.82 -0.16]
 [ 3.26 -1.72  0.41 -2.47]
 [ 1.88  0.67 -0.22 -0.67]
 [ 0.31 -4.62 -1.35 -1.35]
 [ 1.35 -0.53  0.2  -0.97]]
[[-0.94  1.42 -0.85  1.3 ]
 [ 3.91  4.65 -2.96  0.65]
 [-0.22  1.01  1.82 -0.16]
 [ 3.26 -1.72  0.41 -2.47]
 [ 1.88  0.67 -0.22 -0.67]
 [ 0.31 -4.62 -1.35 -1.35]
 [ 1.35 -0.53  0.2  -0.97]]


The following python code creates errors:

`print(np.round( A@C   ,2)), print(' ')`

__ValueError:__ matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

`print(np.round( B@C   ,2)), print(' ')`

__ValueError:__ matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 5)

### Matrix Multiplication in pytorch

In [15]:
# let's create some random matrices with torch
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )
A, B, C1, C2, C2.shape

(tensor([[ 0.1872, -0.8932, -1.0881,  1.4561],
         [-1.0615, -0.5726,  1.1205, -3.2414],
         [ 1.1157, -0.0458, -0.6003, -0.7480]]),
 tensor([[ 0.3551, -0.6101, -0.8523,  0.0645, -1.6795],
         [-1.0105,  1.5285, -1.2411, -0.4446, -1.6650],
         [-0.2434,  0.7241,  0.4172, -3.5439,  0.6795],
         [ 0.2498,  1.1135, -0.4944,  1.0321, -2.5335]]),
 array([[ 0.06017314,  0.25709417, -0.05422435, -0.02063503, -0.03827582,
         -0.05447681,  1.20348992],
        [ 0.96001167, -1.12585273, -0.25482095,  0.79063502,  1.36020087,
          0.88881642,  0.03621376],
        [-0.28390031,  0.23203267,  1.51163924, -1.68289395,  0.71424058,
          0.66262587,  1.35799593],
        [ 0.3587782 ,  0.00694361, -0.27216449, -0.25923406, -1.1569774 ,
          1.55566247,  0.0262297 ]]),
 tensor([[ 0.0602,  0.2571, -0.0542, -0.0206, -0.0383, -0.0545,  1.2035],
         [ 0.9600, -1.1259, -0.2548,  0.7906,  1.3602,  0.8888,  0.0362],
         [-0.2839,  0.2320,  1.5116, -1.6

In [13]:
# matrix multiplication
print(np.round( A@C1  ,2)), print(' ') # 3x4 and 4x7

tensor([[ 0.9500,  2.4600, -1.1600,  3.8500, -2.1300, -3.6600,  1.5900],
        [-3.9800, -2.4600, -1.0900, -3.0200, -2.5500,  3.2700, -1.2100],
        [ 3.2300, -1.6900,  4.4000,  1.5300,  7.0000,  1.6600, -2.0000]],
       dtype=torch.float64)
 


(None, None)

In [16]:
print(np.round( A@C2  ,2)) # 3x4 and 4x7 again

tensor([[-0.0100,  0.8100, -1.8200,  0.7400, -3.6800,  0.7400, -1.2500],
        [-2.0900,  0.6100,  2.7800, -1.4800,  3.8100, -4.7500,  0.1400],
        [-0.0700,  0.1900, -0.7500,  1.1400,  0.3300, -1.6600,  0.5100]])


In [18]:
print(np.round( A@B   ,2)) # 3x4 and 4x5

tensor([[ 1.6000, -0.6500, -0.2200,  5.7700, -3.2600],
        [-0.8800, -3.0300,  3.6900, -7.1300, 11.7100],
        [ 0.4000, -2.0200, -0.7700,  1.4500, -0.3100]])


The following python code creates errors:

`print(np.round( A@B   ,2)), print(' ')`

__RuntimeError:__ mat1 and mat2 shapes cannot be multiplied (3x4 and 5x4)