## 2.1. Data Manipulation

*Studying and coding along with the printed book __„Dive into Deep Learning“__ by Aston Zhang, Zachary C. Lipton, Mu Li & Alexander J. Smola. The accompanying website for the chapter Preliminaries > Data Manipulation can be found at [d2l.ai](https://d2l.ai/chapter_preliminaries/ndarray.html).*

### 2.1.1. Getting started with Data Manipulation

In [1]:
# importing the PyTorch library
import torch

#### __What is a tensor?__

A tensor represents a (possibly multidimensional) array of numerical values. 

- In the one-dimensional case (only one axis is needed for the data) a tensor is called a **vector**.
- With two axes, a tensor is called a **matrix**.
- With *k > 2* axes, we drop the specialized names and just refer to the object as a ***k<sup>th</sup>*-order tensor**.

In [4]:
# creating new tensors prepopulated with values with arange(n)
# creates a vector of evenly spaced values
# it starts at 0 (included) and ends at n (not included). 
# by default the interval size is 1
# by default new tensors are stored in main memory and designated for CPU-based computation
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [6]:
# element of the tensor
x[0]

tensor(0.)

In [8]:
# total number of elements in a tensor
x.numel()

12

In [9]:
# accessing a tensor’s shape (the length along each axis) by inspecting its shape attribute
x.shape

torch.Size([12])

In [12]:
# changing the shape of a tensor without altering its size or values by invoking reshape
# transform vector x to a matrix X with shape (3, 4)
# the elements of the vector are laid out one row at a time: x[3] == X[0, 3]
X = x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [13]:
X[0, 3]

tensor(3.)

In [14]:
X[1, 3]

tensor(7.)

In [16]:
X.numel()

12

If we know the size of a tensor size we can work out one component of the shape with the information we have:
- Given a tensor of size *n* and target shape *(h, w)* we know that *w = n/h*.
- Above example: given a tensor of 12 and target shape (3, w) we know that w = 12/3.

In [18]:
# to automatically infer one component of the shape, we can place a -1 for the shape component that should be inferred automatically 
Y = x.reshape(-1, 4)
Y

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [19]:
Z = x.reshape(3, -1)
Z

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [15]:
# example: a tensor initialized to contain all 0s or 1s
# constructing a tensor with all elements set to 0 and a shape of (2, 3, 4)
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [20]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

#### __Sampling elements randomly from a given probability distribution__

- It can be of advantage to sample each element randomly (and independently) from a given probability distribution. 
- For example, the parameters of neural networks are often initialized randomly. 

In [22]:
# creating a tensor with elements drawn from a standard Gaussian (normal) distribution with mean 0 and standard deviation 1
torch.randn(3,4)

tensor([[ 1.8146,  1.1493,  1.1094, -0.7689],
        [-1.3890, -1.3211,  1.6057,  0.4789],
        [-2.0042,  0.2064, -0.4230, -1.9270]])

### 2.1.2. Indexing and Slicing

In [29]:
# tensor elements cab be accessed by indexing, starting with 0
# a whole ranges of indices can be accessed via slicing (e.g., X[start:stop]), 
## where the returned value includes the first index (start) but not the last (stop)
X[1:3]

tensor([[ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 33.]])

When only one index (or slice) is specified for a *k<sup>th</sup>*-order tensor, it is applied along axis 0.<br/>
Thus, in the previous code, [-1] selects the last row and [1:3] selects the second and third rows.

In [30]:
# to access an element based on its position relative to the end of the list, we can use negative indexing
X[-1]

tensor([ 8.,  9., 10., 33.])

In [25]:
# writing elements of a matrix by specifying indices
print(X)
X[1, 2] = 17
X[2, 3] = 33
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 33.]])

#### __Assigning multiple elements the same value__

In [33]:
#, we apply the indexing on the left-hand side of the assignment operation
# for instance, [:2, :] accesses the first and second rows
## where : takes all the elements along axis 1 (column)
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 33.]])